# Generated by Django 4.2.3 on 2023-08-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_user_name_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="experts",
        ),
    ]
